INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (1, 'ecurieTest');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (2, 'Fnatic');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (3, 'SoloMid');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (4, 'Cloud9');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (5, 'Ninjas');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (6, 'Liquid');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (7, 'Envy');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (8, 'Luminosity');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (9, 'G2');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (10, 'LDLC');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (11, 'FaZe');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (12, 'Atralis');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (13, 'Paris ESport');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (14, 'Natus Vincere');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (15, 'Nova ESport');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (16, 'Invinctus');
INSERT INTO iut_sae.ecurie (ecurie_id, nom_ecurie) VALUES (17, 'Spirit');
