INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (1, 'Nina', 'Girard', 'nins', 'Francais', null, 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (2, 'Sabri', 'A', 'sabsab31', 'Francais', null, 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (3, 'Jean', 'Joueur', 'Joueur71', 'Francais', '2022-11-25', 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (4, 'Pierre', 'Pierre', 'Pierredu89', 'Espagnole', '2022-11-25', 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (5, 'Anna', 'NIETO', 'Axnah_', 'Francais', '2022-11-25', 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (6, 'Joueur34', 'Joueur34', 'Joueur34', 'Francais', '2022-11-25', 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (7, 'Timothe', 'Vanier', 'titou', 'Francais', '2022-11-25', 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (8, 'aeazeae', 'azeazeaze', 'aeazeazeaz', 'Francais', '2022-12-07', 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (9, 'Alex', 'Ponk', 'alexponk', 'Francais', null, 1);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (10, 'Freddy', 'Johansson', 'KRIMZ', 'Suedois', '2016-10-24', 2);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (11, 'William ', 'Merriman', 'mezii', 'Royaume-Uni', '2021-08-03', 2);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (12, 'Nico ', 'Tamjidi', 'nicoodoz', 'Danmark', '2022-06-01', 2);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (13, 'Fredrik ', 'Jørgensen', 'roej', 'Danmark', '2022-06-01', 2);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (14, 'Dion ', 'Derksen', 'flashr', 'Pays-Bas', '2022-06-01', 2);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (15, 'Sean ', 'Gares', 'sgares', 'Etats-Unis', '2016-12-14', 3);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (16, 'Kory ', 'Friesen', 'SEMPHIS', 'Canadanien', '2016-01-19', 3);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (17, 'Pujan', 'Mehta', 'FNS', 'Canadanien', '2016-01-19', 3);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (18, 'Timothy', 'Ta', 'automatic', 'Etats-Unis', '2016-12-14', 3);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (19, 'Daniel', 'Kim', 'vice', 'Etats-Unis', '2016-01-19', 3);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (20, 'Vladislav ', 'Gorshkov', 'nafany', 'Russe', '2022-04-24', 4);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (21, 'Dmitriy ', 'Sokolov', 'sh1ro', 'Russe', '2022-04-24', 4);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (22, 'Timofey ', 'Yakushin', 'interz', 'Russe', '2022-04-24', 4);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (23, 'Sergey ', 'Rykhtorov', 'Ax1Le', 'Kazakhstan', '2022-04-24', 4);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (24, 'Abai ', 'Hasenov', 'HObbit', 'Russe', '2022-04-24', 4);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (25, 'Fredrik', 'Sterner', 'REZ', 'Suedois', '2017-06-12', 5);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (26, 'Hampus', 'Poser', 'Hampus', 'Suedois', '2020-05-19', 5);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (27, 'Ludvig', 'Brolin', 'Brollan', 'Suedois', '2022-03-22', 5);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (28, 'Aleksi', 'Virolainen', 'Aleksib', 'Finlande', '2022-09-08', 5);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (29, 'Daniel', 'Narancic', 'djL', 'Suede', '2022-01-14', 5);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (30, 'soulcas', 'Dom', 'Sulcas', 'Royaume-Uni', '2020-08-07', 6);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (31, 'Jamppi', 'Elias', 'Olkkonen', 'Filande', '2020-08-07', 6);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (32, 'dimasick', 'Dmitriy', 'Matvienko', 'Kazakhstan', '2020-08-07', 6);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (33, 'Redgar', 'Igor', 'Vlasov', 'Pays-Bas', '2020-08-07', 6);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (34, 'nAts', 'Ayaz', 'Akhmetshin', 'Pays-Bas', '2020-08-07', 6);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (35, 'Vincent', 'Cervoni', 'Happy', 'Francais', '2015-02-01', 7);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (36, 'Cédric', 'Guipouy', 'Rpk', 'Francais', '2015-02-01', 7);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (37, 'Adil', 'Benrlitom', 'ScreaM', 'Belge', '2015-02-01', 7);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (38, 'Fabien', 'Fiey', 'kioShiMa', 'Francais', '2015-02-01', 7);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (39, 'Ali', 'Haïnouss', 'hAdji', 'Francais', '2015-02-01', 7);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (40, 'Gabriel', 'Toledo', 'FalleN', 'Bresil', '2015-07-28', 8);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (41, 'Fernando', 'Alvarenga', 'fer', 'Bresil', '2015-07-28', 8);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (42, 'Marcelo', 'David', 'coldzera', 'Bresil', '2015-07-28', 8);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (43, 'Lincoln', 'Lau', 'fnx', 'Bresil', '2015-07-28', 8);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (44, 'Epitacio', 'De Melo', 'TACO', 'Bresil', '2015-07-28', 8);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (45, 'Kenny', 'Schrub', 'KennyS', 'Francais', '2017-02-03', 9);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (46, 'Rémy ', 'Quoniam', 'XTQZZZ', 'Francais', '2022-01-23', 9);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (47, 'Aleksi ', 'Virolainen', 'Aleksib', 'Finaland', '2022-01-23', 9);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (48, 'Audric ', 'Jug', 'JACKZ', 'Francais', '2018-11-26', 9);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (49, 'François ', 'Delaunay', 'AMANEK', 'Francais', '2019-03-07', 9);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (50, 'Richard ', 'Papillon', 'shox', 'Francais', '2017-06-22', 10);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (51, 'Timothée ', 'Démolon', 'DEVIL', 'Francais', '2017-06-22', 10);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (52, 'Julien ', 'Hernandez', 'Krav', 'Francais', '2017-02-21', 10);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (53, 'EValentin ', 'Balbastro', 'mistou', 'Francais', '2016-08-24', 10);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (54, 'Alexandre', 'Forté', 'xms', 'Francais', '2016-08-24', 10);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (55, 'Håvard ', 'Nygaard', 'rain', 'Suisse', '2016-01-20', 11);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (56, 'Helvijs ', 'Saukants', 'brocky', 'Suisse', '2019-09-26', 11);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (57, 'Russel ', 'Dulken', 'Twistzz', 'Suisse', '2021-01-30', 11);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (58, 'Finn ', 'Andersen', 'karrigan', 'Suisse', '2021-02-15', 11);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (59, 'Robin ', 'Kool', 'ropz', 'Suisse', '2022-01-03', 11);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (60, 'Andreas ', 'Hojsleth', 'Xyp9x', 'Danemark', '2016-01-18', 12);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (61, 'Lukas', 'Rossander', 'gla1ve', 'Danemark', '2016-01-18', 12);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (62, 'Benjamin', 'Bremer', 'blameF', 'Danemark', '2016-01-18', 12);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (63, 'Nocolai', 'Reedtz', 'dev1ce', 'Danemark', '2016-01-18', 12);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (64, 'Christian', 'Andersen', 'Buzz', 'Danemark', '2016-01-18', 12);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (65, 'Jean', 'Eude', 'Paris 1', 'Francais', '2022-12-28', 13);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (66, 'Pierre', 'Effeil', 'Paris 2', 'Francais', '2022-12-28', 13);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (67, 'Michel', 'Dufranc', 'Paris 3', 'Francais', '2022-12-28', 13);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (68, 'Leo', 'Dupont', 'Paris 4', 'Francais', '2022-12-28', 13);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (69, 'Frank', 'Du lac', 'Paris 5', 'Francais', '2022-12-28', 13);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (70, 'Zhu ', 'Bocheng', 'paraboy', 'Chinois', '2020-07-09', 15);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (71, 'Zeng ', 'Ronghua', 'coolboy', 'Chinois', '2020-07-09', 15);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (72, 'Xu', 'Yinjun', 'Jimmy', 'Chinois', '2020-07-09', 15);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (73, 'Zhou ', 'Zehai', 'Order', 'Chinois', '2020-07-09', 15);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (74, 'Lin ', 'Yien', 'King', 'Chinois', '2020-07-09', 15);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (75, 'Oleksandr ', 'Kostyliev', 's1mple', 'Ukraine', '2016-08-04', 14);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (76, 'Denis ', 'Sharipov', 'electroNic', 'Ukraine', '2017-11-06', 14);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (77, 'Ilya ', 'Zalutskiy', 'Perfecto', 'Ukraine', '2020-01-24', 14);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (78, 'Valerii ', 'Vakhovskyi', 'b1t', 'Ukraine', '2020-12-20', 14);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (79, 'Viktor ', 'Orudzhev', 'sdy', 'Ukraine', '2022-06-03', 14);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (80, 'Gu', 'Jiaming', 'DeStrRoYeR', 'Chinois', '2020-03-20', 16);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (81, 'Hao', 'Yu', 'rage', 'Chinois', '2021-08-01', 16);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (82, 'Liu', 'Zhiwei', '0i', 'Chinois', '2022-05-01', 16);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (83, 'Tzu-Chi', 'Huang', 'Marek', 'Chinois', '2022-11-15', 16);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (84, 'Jin', 'Xin', 'XyFjin', 'Chinois', '2022-10-01', 16);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (85, 'Leonid ', 'Vishnyakov', 'chopper', 'Russe', '2019-03-03', 17);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (86, 'Boris ', 'Vorobyev', 'magixx', 'Russe', '2019-03-03', 17);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (87, 'Robert ', 'Isyanov', 'Patsi', 'Russe', '2019-03-03', 17);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (88, 'Pavel', 'Ogloblin', 's1ren', 'Russe', '2019-03-03', 17);
INSERT INTO iut_sae.joueur (id, prenom, nom, pseudo, nationnalite, entree_pro, ecurie) VALUES (89, 'Ihor ', 'Zhdanov', 'w0nderful', 'Ukrainien', '2019-03-03', 17);
